### PR TITLE
Update to Mixins 0.8 

### PR DESCRIPTION
**Pull request by idnthvn**
Updated and built to mixin 0.8   I am not a coder by any means, but looked at others and seen how they did it.   Hope this works?

### CODE REVIEW

**Comment by TerminatorNL** [comment]
I see this was closed, are there any issues you'd like to iron out first?

**Comment by idnthvn** [comment]
I wish i was a coder :P, I understand basics and reading some, but understanding how everything works is beyond me. I probably should make my own mod/plugin and learn it better :P. Anyways, i thought changing it over would of just fixed it, but crashes during a transform.   When applying custom transformer "MixinWorldServerSponge", it then crashs with "Unable to transform class (net.minecraft.world.WorldServer)"

Here is my latest log with just sponge and TiQuality. 
[latest.log](https://github.com/TerminatorNL/Tiquality/files/4348597/latest.log)

I actually worked on this, well tried, because it worked great on the server, however i needed to update sponge to fix other issues, and the first 0.8 mixin update it was the one that i needed, and well, you know, it didnt work together :P   anyways. Any input or let me know would be great. Mixin 0.8 changelog mentioned that the preApply and postApply has changed that somehow needed to do a new MethodNode?  I was lost, like i said, i am in no way a coder. (just a guy who loves to learn and tinker)

**Comment by TerminatorNL** [comment]
I see. I want to give you a little bit of credit though, when I get around to fixing this I will merge this and make it work. Thank you for your efforts!

**Comment by idnthvn** [comment]
if you have a discord or something, i would love to learn more about how to read the error more and learn how to fix things like this. maybe even just watch and learn type of thing.

**Pull request closed without merging**
